### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Tdub1229** [sandialabs/SandiaDecay#1]
[ 30%] Building CXX object tools/CMakeFiles/minimize_xml_file.dir/minimize_xml_file.cpp.o
/home/ed/SandiaDecay/tools/minimize_xml_file.cpp: In function ‘int main(int, char**)’:
/home/ed/SandiaDecay/tools/minimize_xml_file.cpp:246:117: error: no matching function for call to ‘find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, const string&)’
 _iterator pos = std::find( gamma_uuid.begin(), gamma_uuid.end(), gchild_uuid );
                                                                              ^
In file included from /usr/include/c++/7/bits/locale_facets.h:48:0,
                 from /usr/include/c++/7/bits/basic_ios.h:37,
                 from /usr/include/c++/7/ios:44,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /home/ed/SandiaDecay/tools/minimize_xml_file.cpp:26:

**Comment by ipelupessy** [comment]
I got the same error..

**Comment by wcjohns** [comment]
Hi, I'm really sorry that I missed this issue!
I didn't have notifications from GitHub turned on in 2019, and never noticed it.  I hope you were able to work around it.
  -will
