### ISSUE TITLE
missing #include <algorithm>

### ISSUE THREAD

**Issue by harperrc** [sandialabs/SandiaDecay#4]
in tools/minimize_xml_file.cpp & examples/sandia_decay_example.cpp failed to compile on ubuntu 22.04 using g++ without adding <algorithm> to both (could not find std::find())
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by wcjohns** [comment]
Thank you for reporting this!

I'm not quite sure why it compiled on macOS/Windows.
