### ISSUE TITLE
Bug in internalIndex in NuclideMixture

### ISSUE THREAD

**Issue by kevin-servaenergy** [sandialabs/SandiaDecay#5]
Hi I'm running into a bug for the method `NuclideMixture::internalIndex(int z, int atomic_mass, int iso )`.
I'm getting an exception when the nuclide should definitely be in the mixture.

I noticed in the implementation that the `Nuclide->atomicMass` field (float) is compared with the parameter `atomic_mass` (int) which would not be equal most of the time.
```
#include "SandiaDecay/SandiaDecay.h"
#include <cstdio>

using namespace SandiaDecay;

int main(int arg, char * argv[]) {
   SandiaDecayDataBase db(argv[1]);
   NuclideMixture mix;
   const Nuclide * n = db.nuclide("Co60");
   mix.addNuclideByActivity(n, 10.0f);
   printf("Mix Idx1: %i\n", mix.internalIndexNumber(n));
   printf("Mix Idx2: %i\n", mix.internalIndexNumber(n->atomicNumber, n->massNumber, n->isomerNumber));
   return 0;
}

```

Output: 
```
Mix Idx1: 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Z=27 AN=60, ISO=0 is not in this NuclideMixture.
```

**Comment by wcjohns** [comment]
Great catch - thank you for finding this!
In addition to fixing the issue (commit 59c29c1), I also slightly improved the documentation of the function.
Again, thank you,
  -will
